# Junyi Zhao     jzhao33@ucsc.edu
# Huaning Wang   hwang161@ucsc.edu
# Wenhao Ge      wge1@ucsc.edu

benchmark: benchmark.c
	cc -o benchmark benchmark.c -lfl
	chmod +x benchmark

clean:
        rm -f ./benchmark *.core

